/* Catálogos — datos reales Cap Cana */
export const PROYECTOS = [
  [1,"ARRASTRE","Amenidades Caletón Residences"],[2,"ARRASTRE","Caletón Fase 6"],
  [3,"ARRASTRE","Residencia del Parque"],[4,"ARRASTRE","Green Village Condo Fase 1"],
  [5,"ARRASTRE","Driving Range Condo"],[6,"ARRASTRE","Desarrolladores Canas Sur"],
  [7,"ARRASTRE","Paseo del Farallón"],[8,"ARRASTRE","Green Village Condo 2"],
  [9,"ARRASTRE","The Falls Fase 1"],[10,"ARRASTRE","The Falls Fase 2"],
  [11,"ARRASTRE","Ocean Lake"],[12,"ARRASTRE","Paseo las Canas"],
  [13,"ARRASTRE","Golden Lakes"],[14,"ARRASTRE","Lake District"],
  [15,"ARRASTRE","Juanillo Village Fase 1"],[16,"NUEVOS","Caletón Fase 7"],
  [17,"NUEVOS","Racquet Village Clúster III"],[18,"NUEVOS","Golf View Condos"],
  [19,"NUEVOS","Torneo ATP"],[20,"NUEVOS","Caletón Luxury"],
  [21,"VIALES","Boulevard de las Torres"],[22,"VIALES","20 Kms de Cart Path (5 KMS)"],
  [23,"VIALES","Mantenimiento Vía de Servicios"],[24,"VIALES","Otros Proyectos Menores"],
  [25,"VIALES","Garden View"],[26,"GOLF","Campo de Golf Las Iguanas"],
  [27,"PASIVOS","Otros Compromisos Punta Palmera"],[28,"PASIVOS","Ciudad las Canas Norte"],
  [29,"PASIVOS","Ciudad las Canas Sur"],[30,"PASIVOS","MCC"],
  [31,"PASIVOS","Green Village Residences (Áreas públicas y Kioskos)"],
  [32,"PASIVOS","Las Palmitas 1 y 2"],[33,"PASIVOS","Serenissima e Isla Puerto"],
  [34,"PASIVOS","Punta Maravilla"],[35,"PASIVOS","Condo Las Iguanas"],
  [36,"PASIVOS","The Legends"],[37,"PASIVOS","Parques Ciudad las Canas"],
  [38,"PASIVOS","Restructuración edificio fase II"],[39,"PASIVOS","Playa Juanillo"],
  [40,"OTROS","Parqueo Control de Acceso"],[41,"OTROS","Vía hacia Centro de Generación Eléctrica"],
  [42,"OTROS","P18 Alfa"],[43,"OTROS","P18 Bravo"],[44,"OTROS","Iron Man 70.3"],
  [45,"OTROS","Lagunas 58"],[46,"OTROS","Muelle Seco la Marina"],[47,"OTROS","Vertedero"],
  [48,"OTROS","Ampliación Acueducto"],[49,"OTROS","Distribuidor tráfico Racquet Village"],
  [50,"OTROS","CCHS"],[51,"OTROS","Iguanas Bike Nine"],[52,"OTROS","Fiordos del Dorado"],
  [53,"OTROS","Caletón Fase 5"],[54,"OTROS","Caletón Fase 4"],[55,"OTROS","Caletón Fase 3"],
  [56,"OTROS","Oficinas Control del Acceso"],[57,"OTROS","Cart Path Fundadores 21-22"],
];

export const PARTIDAS = [
  [1,"Infraestructura vial","Pavimento","Estudios de Suelos"],
  [2,"Infraestructura vial","Pavimento","Topografía"],
  [3,"Infraestructura vial","Pavimento","Movilización de Equipos"],
  [4,"Infraestructura vial","Pavimento","Sub-rasante terminada"],
  [5,"Infraestructura vial","Pavimento","Imprimación"],
  [6,"Infraestructura vial","Pavimento","Asfaltado"],
  [7,"Infraestructura vial","Obras complementarias","Canaletas"],
  [8,"Infraestructura vial","Obras complementarias","Bordillos"],
  [9,"Infraestructura vial","Obras complementarias","Registro pluviales"],
  [10,"Infraestructura vial","Iluminación","Bases de luminarias"],
  [11,"Infraestructura vial","Iluminación","Alimentación eléctrica"],
  [12,"Infraestructura vial","Iluminación","Postes con luminarias"],
  [13,"Infraestructura vial","Cart path","Sub-rasante terminada"],
  [14,"Infraestructura vial","Cart path","Losa rodadura"],
  [15,"Infraestructura vial","Señalización","Señalización horizontal"],
  [16,"Infraestructura vial","Señalización","Señalización vertical"],
  [17,"Infraestructura hidrosanitaria","Líneas","Movimiento de tierras"],
  [18,"Infraestructura hidrosanitaria","Líneas","Tuberías colocadas"],
  [19,"Infraestructura hidrosanitaria","Acometidas","Registros condominios"],
  [20,"Infraestructura hidrosanitaria","Acometidas","Registros unifamiliares"],
  [21,"Infraestructura hidrosanitaria","Acometidas","Registros aguas negras"],
  [22,"Infraestructura hidrosanitaria","Cárcamos","Movimiento de tierras"],
  [23,"Infraestructura hidrosanitaria","Cárcamos","Estructura cárcamo"],
  [24,"Infraestructura hidrosanitaria","Cárcamos","Equipamiento"],
  [25,"Infraestructura eléctrica y telecom","Líneas","Movimiento de tierras"],
  [26,"Infraestructura eléctrica y telecom","Líneas","Tuberías colocadas"],
  [27,"Infraestructura eléctrica y telecom","Líneas","Instalaciones eléctricas"],
  [28,"Infraestructura eléctrica y telecom","Líneas","Instalaciones telecomunicaciones"],
  [29,"Paisajismo","Césped","Césped"],
  [30,"Paisajismo","Tierra negra","Tierra negra"],
  [31,"Paisajismo","Arbolado","Arbolado"],
  [32,"Estructuras Especiales","Garita entrada","Movimiento de tierras"],
  [33,"Estructuras Especiales","Garita entrada","Estructura de garita"],
  [34,"Estructuras Especiales","Garita entrada","Equipamiento de garita"],
  [35,"Estructuras Especiales","Garita entrada","Cruces"],
  [36,"Estructuras Especiales","Garita entrada","Obras Complementarias"],
  [37,"Estructuras Especiales","Garita entrada","Dispositivos de acceso y Data"],
  [38,"Estructuras Especiales","Puentes","Movimiento de tierras"],
  [39,"Estructuras Especiales","Puentes","Estructura Puentes"],
  [40,"Estructuras Especiales","Puentes","Terminaciones Puentes"],
  [41,"Estructuras Especiales","Lagos - Canales","Movimiento de tierras"],
];

export const ACTIVIDADES = [
  ["A-001","Sondeos",1,"UND"],["A-002","Levantamientos y Replanteo de áreas",2,"Días"],
  ["A-003","Movilización de Equipos",3,"UND"],["A-004","Desbroce Vial",4,"M2"],
  ["A-005","Desbroce Solares",4,"M2"],["A-006","Acarreos de Bote",4,"M3*KM"],
  ["A-007","Acarreos de Material",4,"M3*KM"],["A-008","Relleno Vías con Caliche",4,"M3S"],
  ["A-009","Relleno Servidumbre",4,"M3C"],["A-010","Corte de Terreno",4,"M3N"],
  ["A-011","Fresado Vías",4,"M3N"],["A-012","Corte de Capa Vegetal",4,"M3N"],
  ["A-013","Saneamiento de sub-rasante",4,"M3C"],["A-014","Terminación de Vías",4,"M2"],
  ["A-015","Escarificación de Vías",4,"M2"],["A-016","Riego de imprimación",5,"M2"],
  ["A-017","Riego de Adherencia",6,"M2"],["A-018","Suministro y colocación de asfalto",6,"M3S"],
  ["A-019","Canaletas",7,"ML"],["A-020","Bordillos",8,"ML"],
  ["A-021","Imbornales",9,"UND"],["A-022","Bases de luminarias",10,"UND"],
  ["A-023","Zanja alimentación iluminación vial",11,"ML"],["A-024","Cableado alimentación iluminación",11,"ML"],
  ["A-025","Postes de aluminio de 4 m",12,"UND"],["A-026","Postes de aluminio de 6 m",12,"UND"],
  ["A-027","Postes de aluminio de 9 m",12,"UND"],["A-028","Luminarias",12,"UND"],
  ["A-029","Relleno Cart Path",13,"M3C"],["A-030","Aceras",14,"M2"],
  ["A-031","Riego de imprimación cart path",14,"M2"],["A-032","Asfalto cart path",14,"M3S"],
  ["A-033","Líneas Blancas",15,"ML"],["A-034","Líneas Amarillas",15,"ML"],
  ["A-035","Pasos Peatonales",15,"M2"],["A-036","Línea de Pare",15,"M2"],
  ["A-037","Flechas direccionales",15,"UND"],["A-038","Parqueos",15,"UND"],
  ["A-039","Diseños Simbolizados",15,"ML"],["A-040","Boyas grandes reductores",15,"UND"],
  ["A-041","Policías Acostados Caucho",15,"ML"],["A-042","Ojos de Gato",15,"UND"],
  ["A-043","Señalización vertical",16,"UND"],["A-044","Excavación Zanja Aguas",17,"M3S"],
  ["A-045","Excavación Cruces Aguas",17,"M3S"],["A-046","Excavación Sobreancho Aguas",17,"M3S"],
  ["A-047","Suministro de Arena Aguas",18,"M3S"],["A-048","Tubería Agua Potable 4\" PEAD",18,"ML"],
  ["A-049","Tubería Agua Potable 6\" PEAD",18,"ML"],["A-050","Tubería Agua Potable 8\" PEAD",18,"ML"],
  ["A-051","Tubería Agua Potable 10\" PEAD",18,"ML"],["A-052","Tubería Agua Potable 12\" PEAD",18,"ML"],
  ["A-053","Tubería Agua Potable 16\" PEAD",18,"ML"],["A-054","Tubería Agua Riego 4\" PEAD",18,"ML"],
  ["A-055","Tubería Agua Riego 6\" PEAD",18,"ML"],["A-056","Tubería Agua Riego 8\" PEAD",18,"ML"],
  ["A-057","Tubería Agua Riego 10\" PEAD",18,"ML"],["A-058","Tubería Agua Riego 12\" PEAD",18,"ML"],
  ["A-059","Tubería Agua Riego 16\" PEAD",18,"ML"],["A-060","Tubería Impulsión 4\" PEAD",18,"ML"],
  ["A-061","Tubería Impulsión 6\" PEAD",18,"ML"],["A-062","Tubería Impulsión 8\" PEAD",18,"ML"],
  ["A-063","Tubería Impulsión 10\" PEAD",18,"ML"],["A-064","Tubería Impulsión 12\" PEAD",18,"ML"],
  ["A-065","Tubería Sanitaria 4\" corrugada",18,"ML"],["A-066","Tubería Sanitaria 6\" corrugada",18,"ML"],
  ["A-067","Tubería Sanitaria 8\" corrugada",18,"ML"],["A-068","Tubería Sanitaria 10\" corrugada",18,"ML"],
  ["A-069","Tubería Sanitaria 12\" corrugada",18,"ML"],["A-070","Prueba Hidrostática",18,"UND"],
  ["A-071","Hidrantes",18,"UND"],["A-072","Relleno Zanjas Aguas",18,"M3S"],
  ["A-073","Cruces Hidrosanitarios 10\"",18,"UND"],["A-074","Cruces Hidrosanitarios 12\"",18,"UND"],
  ["A-075","Cruces Hidrosanitarios 16\"",18,"UND"],["A-076","Cruces Hidrosanitarios 36\"",18,"UND"],
  ["A-077","Relleno Cruces Hidrosanitarios",18,"M3C"],["A-078","Piezas Especiales Principales",18,"UND"],
  ["A-079","Registros Acometidas Condominios",19,"UND"],["A-080","Acometida Condominios 6\" Potable",19,"UND"],
  ["A-081","Acometida Condominios 4\" Potable",19,"UND"],["A-082","Acometida Condominios 2\" Potable",19,"UND"],
  ["A-083","Acometida Condominios 1½\" Potable",19,"UND"],["A-084","Acometida Condominios 2\" Riego",19,"UND"],
  ["A-085","Acometida Condominios 1½\" Riego",19,"UND"],["A-086","Acometida Condominios 6\" Impulsión",19,"UND"],
  ["A-087","Acometida Condominios 4\" Impulsión",19,"UND"],["A-088","Registros Acometidas Unifamiliares",20,"UND"],
  ["A-089","Acometida Unifamiliar 2\" Potable",20,"UND"],["A-090","Acometida Unifamiliar 1½\" Potable",20,"UND"],
  ["A-091","Acometida Unifamiliar 4\"@1\" Pot. y Riego",20,"UND"],["A-092","Acometida Unifamiliar 2\" Riego",20,"UND"],
  ["A-093","Acometida Unifamiliar 4\"@1½\" Riego",20,"UND"],["A-094","Acometida Unifamiliar 1\" Riego",20,"UND"],
  ["A-095","Registros Sanitarios",21,"UND"],["A-096","Replanteo cárcamos",22,"UND"],
  ["A-097","Excavación de cárcamo",22,"M3"],["A-098","Acondicionamiento de terreno",22,"M2"],
  ["A-099","Encofrado de Platea",23,"M2"],["A-100","Armado de Platea",23,"M2"],
  ["A-101","Vaciado Hormigón de Platea",23,"M3"],["A-102","Armado de Muros",23,"M2"],
  ["A-103","Encofrado de Muros",23,"M2"],["A-104","Vaciado Hormigón de Muros",23,"M2"],
  ["A-105","Encofrado de Losa Superior",23,"M2"],["A-106","Armado de Losa",23,"M2"],
  ["A-107","Vaciado Hormigón de Losa",23,"M3"],["A-108","Elaboración de Pozo Filtrante",23,"UND"],
  ["A-109","Terminación e Impermeabilización",23,"M2"],["A-110","Tapas de Fibra de Vidrio",23,"UND"],
  ["A-111","Equipamiento y Piezas de Cárcamo",24,"UND"],["A-112","Excavación Zanja Eléctricas",25,"M3S"],
  ["A-113","Excavación Cruces Eléctricas",25,"M3S"],["A-114","Excavación Sobreancho Eléctricas",25,"M3S"],
  ["A-115","Suministro de Arena Eléctrica",26,"M3S"],["A-116","Tubería Eléctrica 6\" PVC SDR26",26,"ML"],
  ["A-117","Tubería Eléctrica 4\" PVC SDR26",26,"ML"],["A-118","Tubería Eléctrica 3\" PVC SDR26",26,"ML"],
  ["A-119","Tubería Eléctrica 2\" PVC SDR26",26,"ML"],["A-120","Tubería Eléctrica 1½\" PVC SDR26",26,"ML"],
  ["A-121","Tubería Eléctrica 1\" PVC SDR26",26,"ML"],["A-122","Relleno Zanjas Eléctricas",26,"M3S"],
  ["A-123","Registros de Transformadores",27,"UND"],["A-124","Bases para Seccionadoras",27,"UND"],
  ["A-125","Bases para Transformadoras",27,"UND"],["A-126","Registros Eléctricos de Solares",27,"UND"],
  ["A-127","Cableado eléctrico",27,"ML"],["A-128","Seccionadora",27,"UND"],
  ["A-129","Transformador",27,"UND"],["A-130","Módulos de Medición",27,"UND"],
  ["A-131","Cableado de Data (Fibra Óptica)",28,"ML"],["A-132","Colocación de grama",29,"M2"],
  ["A-133","Tierra Negra Cernida",30,"M3"],["A-134","Tierra Negra Arcillosa",30,"M3"],
  ["A-135","Instalación de árboles",31,"UND"],["A-136","Excavación Zapatas",32,"M3"],
  ["A-137","Zapatas",33,"M3"],["A-138","Columnas",33,"M3"],["A-139","Muros",33,"M3"],
  ["A-140","Vigas",33,"M3"],["A-141","Pañetes",33,"M2"],["A-142","Pisos",33,"M2"],
  ["A-143","Revestimientos",33,"M2"],["A-144","Pintura",33,"M2"],["A-145","Techos",33,"M2"],
  ["A-146","Estructura metálica",33,"M2"],["A-147","Estructura cañas",33,"M2"],
  ["A-148","Louvers",33,"M2"],["A-149","Instalaciones sanitarias",34,"UND"],
  ["A-150","Instalaciones eléctricas",34,"UND"],["A-151","Cruce eléctricos y Data",35,"UND"],
  ["A-152","Cruce Hidrosanitarios",35,"UND"],["A-153","Cruce barras acceso y cámaras",35,"UND"],
  ["A-154","Bordillos (Garita e isletas)",36,"ML"],["A-155","Aceras garita",36,"M2"],
  ["A-156","Canalizaciones data y acceso",37,"ML"],["A-157","Instalación barras control acceso",37,"UND"],
  ["A-158","Instalación de cámaras",37,"UND"],["A-159","Excavaciones Zapatas puentes",38,"M3"],
  ["A-160","Pilotes",39,"M3"],["A-161","Zapatas puentes",39,"M3"],
  ["A-162","Muros Hormigón Armado",39,"M3"],["A-163","Losas Puentes",39,"M3"],
  ["A-164","Terminaciones Superficies",40,"M2"],["A-165","Corte Terreno Mojado (Dinamitado)",41,"M3"],
  ["A-166","Corte Terreno Mojado (Martillo)",41,"M3"],["A-167","Dragado",41,"M3"],
  ["A-168","Acarreos de Material Lagos",41,"M3*KM"],["A-169","Corte de Terreno Seco",41,"M3N"],
  ["A-170","Corte de Terreno Lagos",41,"M3N"],["A-171","Fresado Lagos",41,"M3N"],
];

export const CONTRATISTAS = [
  "ALEXANDER CONTRERAS Y ASOC.","ALITO EIRL","ALTATEC COMUNICATIONS","ANEUDI MANUEL MAÑÓN",
  "ASA - ARMADURA SOFÍA","BLUEWAVE","BREMA","CARLOS RODRÍGUEZ","CODELPA","COHIDA",
  "CONSTRUCTORA MACDOUGALL","CONSTRUVESA","CRAMA","DIOMENE DEL CARMEN","ELECTROVAL",
  "EMINSA","EYTPC","FAGENCA","FRANCISCO AQUINO","GARZA","GED","GEMSA","GEOCONSULT",
  "GLOBAL NÁUTICA","GMA GRACIANO MATOS","GONDAR COMERCIAL","GREEN GARDEN","GRUPO JOSEDA",
  "GRUPO SAILLANT","INFRADOM","INGTECCO","KAIZEN","KMA","LERAF","LETYMAR","LM INGENIEROS",
  "LOMARENAS","MENDOX","MEP ENGINEERING","RAAS GROUP","REMIX","RIGHT CONSTRUCTION","ROT",
  "SANESTO MG","SMB SINERGÍA","SORGEF","SUPLIPUCANSA","SYMMET INGENIERÍA","TARGET-LUX",
  "DESARROLLO VIAL","ENTESER",
];

export const USUARIOS_INICIALES = [
  { correo:"jramos@capcana.com", nombre:"J. Ramos", rol:"Admin" },
  { correo:"juanalbertoramos2009@hotmail.com", nombre:"J. Genere", rol:"Ingeniero" },
  { correo:"p.mercedes@capcana.com", nombre:"P. Mercedes", rol:"Ingeniero" },
  { correo:"s.guerrero@capcana.com", nombre:"S. Guerrero", rol:"Supervisor" },
  { correo:"p.urraca@capcana.com", nombre:"P. Urraca", rol:"Ingeniero" },
];


export const ESTADOS = { Borrador:"#8A8578", Enviado:"#B07D10", Validado:"#2E7D4F", Rechazado:"#B3462E" };
